config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  namespace :api do
    namespace :v1 do
      resources :posts, only: [:index, :create] do
        resources :comments, only: [:index, :create]
      end
    end
  end

  resources :posts, only: [:index, :new] do
    resources :comments, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  scope :with_cache, -> { select(:id, :author, :content, :post_id).order(created_at: :desc) }
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, autosave: true, dependent: :destroy

  scope :with_cache, -> { select(:id, :title, :content).order(created_at: :desc) }
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ActionController::API
  include CommentsConcern

  helper_method :current_post
  helper_method :current_comment
  
  def index
    render json: current_post.comments.with_cache
  end

  def create
    current_comment.attributes = comment_params
    current_comment.save
    render json: { id: current_comment.id, author: current_comment.author, comment: current_comment.content, post_id: current_comment.post_id }
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ActionController::API
  include PostsConcern

  before_action :set_posts, only: :index
  
  def index
    render json: @posts
  end

  def create
    post = Post.create(post_params)
    render json: { id: post.id, title: post.title, content: post.content }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_count_posts
  
  protected

    def set_count_posts
      @count_posts = Post.count
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include CommentsConcern
  helper_method :current_post
  helper_method :current_comment
  
  def index
  end
end

app/controllers/concerns/comments_concern.rb
module CommentsConcern
  extend ActiveSupport::Concern

  protected

    def current_post
      @current_post ||= Post.with_cache.find(params[:post_id])
    end

    def current_comment
      @comment ||= current_post.comments.build
    end

    def comment_params
      params.require(:comment).permit(:author, :content)
    end
end

app/controllers/concerns/posts_concern.rb
module PostsConcern
  extend ActiveSupport::Concern

  protected

    def set_posts
      @posts ||= Post.with_cache
    end

    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include PostsConcern

  before_action :set_posts, only: :index
  
  def index
  end

  def new
    @post = Post.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%=form_with model: comment, url: '#', data: { reflex: "submit->CommentReflex#submit" } do |f| %>
  <%= f.text_field :author, placeholder: 'Enter with the author or leave blank for anonymous', class: 'form-control mb-2' %>
  <%= f.text_area :content, placeholder: 'Enter with the content', class: 'form-control mb-2' %>
  <%= f.submit 'Create', class: 'btn btn-primary btn-sm' %>
<% end %>

app/views/comments/_table_row.html.erb
<tr>
  <td><%=comment.author.blank? ? 'Anonymous' : comment.author %></td>
  <td><%=comment.content%></td>
</tr>

app/views/comments/index.html.erb
<h3>It's time to create a Comment for: <%=current_post.title%></h3>

<div id="comment-form-<%=current_post.id%>">
  <%= render partial: "form", locals: { comment: current_comment }%>
</div>

<hr />
<h5>List of Comments</h5>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Author</th>
      <th>Content</th>
    </tr>
  </thead>

  <tbody id="comments-for-<%=current_post.id%>">
    <%=render partial: "table_row", collection: current_post.comments.with_cache.order(created_at: :desc), as: :comment %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StimlusReflexPosts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container h-100">
      <div class="row mt-4 justify-content-center align-items-center">
        <div class="col-12">
          <h2>StimulusReflexPosts
            <small id="posts-count">Total of posts <%=@count_posts%></small>
          </h2>
          <div class="btn-group mt-2" role="group" aria-label="Application Actions">
            <%= link_to "Dashboard", root_path, class:"btn btn-primary" %>
            <%= link_to "Create Post", new_post_path, class:"btn btn-secondary" %>
          </div>
          <hr />
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%=form_with model: post, data: { reflex: "submit->PostReflex#submit" } do |f| %>
  <%= f.text_field :title, placeholder: 'Enter with the title', class: 'form-control mb-2' %>
  <%= f.text_area :content, placeholder: 'Enter with the content', class: 'form-control mb-2' %>
  <%= f.submit 'Create', class: 'btn btn-primary btn-sm' %>
<% end %>

app/views/posts/_post.html.erb
<div class="card mb-2 bg-light">
  <div class="card-header"><h4><%=post.title%></h4></div>
  <div class="card-body">
    <div class="card-text"><%=post.content%></div>
  </div>
  <div class="card-footer">
    <%= link_to  "Comments", post_comments_path(post), class:"btn btn-secondary btn-sm" %>
  </div>
</div>

app/views/posts/index.html.erb
<h3>List of Posts</h3>

<div id="posts">
  <%=render partial: "post", collection: @posts%>
</div>

app/views/posts/new.html.erb
<h3>Create your Posts</h3>

<div id="post-form">
  <%= render partial: "form", locals: { post: @post }%>
</div>